### ISSUE TITLE
Implement `std::error::Error` for `exempi::Error` and `exempi_sys::XmpError`

### ISSUE THREAD

**Issue by genbattle** [hfiguiere/exempi-rs#4]
I'm currently trying to use the `anyhow` crate with some errors produced by `exempi` (e.g. from `Xmp::set_property`), but I have to do some manual wrapping instead of using the [`anyhow::Context`](https://docs.rs/anyhow/1.0.32/anyhow/trait.Context.html) trait because exempi's error types don't implement the standard [`Error`](https://doc.rust-lang.org/std/error/trait.Error.html) trait.

I would really appreciate it if all of exempi's error types implement the `Error` trait, as it would greatly improve interoperability with Rust's error ecosystem. The implementation could be as simple as:

```rust
impl std::error::Error for XmpError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        None
    }
}
```

**Comment by hfiguiere** [comment]
Fixed.

Thanks.
